name: lint

on:
  pull_request:

jobs:
  shell:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run shellcheck
        run: shellcheck --severity=warning bootstrap/*.sh provision.sh

  ansible:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install ansible-lint
        run: pipx install ansible-lint==6.22 "ansible-core==2.18"

      - name: Install collection requirements
        run: ansible-galaxy collection install -r requirements.yml

      - name: Run ansible-lint
        run: ansible-lint playbooks/
